/**
 * Asks the installed Better Auth what tables this configuration needs.
 * Used by the generator that writes `schema.sql` and by the test that keeps it
 * honest; never at runtime, where the checked-in file is what runs.
 */
import type { Database } from "bun:sqlite";
import { getMigrations } from "better-auth/db/migration";

import { authOptions } from "./auth.ts";

const HEADER = `-- Generated by scripts/generate-schema.ts from the installed Better Auth and
-- the plugin configuration in src/auth.ts. Do not edit; regenerate.
`;

export async function compileSchema(db: Database): Promise<string> {
  // The values other than `db` do not shape the schema, so any will do.
  const migrations = await getMigrations(
    authOptions({ db, baseURL: "http://localhost", secret: "schema-generation-only".padEnd(32, "-") }),
  );
  return HEADER + (await migrations.compileMigrations());
}
